# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  backend-Payroll:
    image: backend-Payroll:qa
    container_name: backend-Payroll
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5200:80
    environment:
      - ASPNETCORE_ENVIRONMENT=QA
      - Apis:UrlClientes=http://api-clientes.qa.seguros.local/clientes/
      - Apis:UrlProductos=http://api-productos.qa.seguros.local/productos/
      - API_BASE_PATH=/backend-Payroll
